### ISSUE TITLE
Update to 6.0.6

### ISSUE THREAD

**Issue by fboucquez** [ichuan/bower-aui#2]
Hi there, thank you for providing the packages in a nice bower way. 

Could you upload latests version to your repo?

https://docs.atlassian.com/aui/latest

Cheers
Fernando

**Comment by ichuan** [comment]
Hi, sorry for the delay. I've updated it to v6.0.6

**Comment by fboucquez** [comment]
Awesome! Thank you again!

On Feb 19, 2017 11:46 PM, "yc" <notifications@github.com> wrote:

Hi, sorry for the delay. I've updated it to v6.0.6

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ichuan/bower-aui/issues/2#issuecomment-280975342>, or mute
the thread
