### ISSUE TITLE
Upload AUI 7.7.0

### ISSUE THREAD

**Issue by fboucquez** [ichuan/bower-aui#3]
Hi ichuan, 

Thank you for keeping this repo. 

Would it be possible to upload aui[ 7.7.0](https://docs.atlassian.com/aui/7.7.0)?

Cheers
Fernando

**Comment by ichuan** [comment]
Hi, thanks for letting me know. I've updated all AUI versions since v6.0.8

By the way, bower seems dying, they recommend switching to npm/yarn, and the official atlassian AUI package is at https://www.npmjs.com/package/@atlassian/aui
